[package]
name = "linear_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "linear_rs"
crate-type = ["rlib", "staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
