name: linalgs

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: check
        run: echo "$PWD"

      - name: build
        run: |
          cd "$PWD"/c-examples/linalgs-c/src
          . build.sh

      - name: pack
        run: |
          zip jcvf libs.zip "$PWD"/c-examples/linalgs-c/src/output/liblinalgs.a "$PWD"/c-examples/linalgs-c/src/linalgs.h
          zip jcvf src.zip "$PWD"/c-examples/linalgs-c/src/linalgs.c "$PWD"/c-examples/linalgs-c/src/linalgs.h

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            libs.zip
            src.zip
