name: matrix

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: check
        run: echo "$PWD"

      - name: build
        run: |
          cd "$PWD"/c-examples/matrix-c/src
          . build.sh

      - name: pack
        run: |
          mkdir libs
          cp "$PWD/c-examples/matrix-c/output/matrix/libmatrix.a" libs/
          cp "$PWD/c-examples/matrix-c/src/matrix/include/matrix" -r libs/
          zip -Jqr libs.zip libs/
          rm -r libs/
          mkdir src
          cp "$PWD/c-examples/matrix-c/src/matrix/include/matrix" -r src/
          cp "$PWD/c-examples/matrix-c/src/matrix/matrix.c" libs/
          cp "$PWD/c-examples/matrix-c/src/matrix/matrix-ext.c" libs/
          zip -Jqr src.zip src/
          rm -r src/

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            libs.zip
            src.zip
